apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-test-from-dockerfile
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-accelerator
    #apps.tanzu.vmware.com/has-tests: true
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  params:
  - name: dockerfile
    value: ./Dockerfile
  source:
    git:
      url: https://github.com/drawsmcgraw/python-test.git
      ref:
        branch: main
